version: '3.9'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/geo_fastapi
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - mongo_db


  mongo_db:
    image: mongo
    volumes:
      - mongo_data:/var/lib/mongo/data/
    env_file:
      - .env
    ports:
      - 27017:27017
    networks:
      - default
      - service-proxy

networks:
  service-proxy:

volumes:
  mongo_data:
